### PR TITLE
Updated dependencies to support Golang 1.7 and newer Docker lib. Minor fixes.

### LINKED ISSUE #24: Crash while running default profile
```
➜  actuary git:(master) docker run -v /var/run/docker.sock:/var/run/docker.sock actuary -f default.toml
...
2016/09/05 01:06:25 Running Audit: Container Runtime
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x866560, 0xc820014040)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/diogomonica/actuary/actuary.CheckSSHRunning(0xc8200ca180, 0xc8200f8b80, 0x3b, 0x40, 0x0, 0x0, 0x40, 0x26, 0xc8200e7600, 0x4, ...)
    /go/src/github.com/diogomonica/actuary/actuary/runtime.go:122 +0x8a8
main.main()
    /go/src/github.com/diogomonica/actuary/actuary.go:74 +0x5f9
```

### PR DESCRIPTION
**Pull request by zuBux**
Changes to comply with newest versions of the API. Fixes #24

### CODE REVIEW

**Comment by zuBux** [comment]
This is strange. The Dockerfile compiles fine on my machine.

**Comment by zuBux** [comment]
I started working on actuary again. New commits don't seem to trigger CircleCI build jobs.

**Comment by diogomonica** [comment]
LGTM.

CircleCI seems to have the job: https://circleci.com/gh/diogomonica/actuary/39

**Comment by zuBux** [comment]
Job 39 is for commit `051287c`  but last commit is `cb75c5b`

**Pull request merged**
